LOCK TABLES `academic_participant` WRITE;

INSERT INTO `academic_participant` VALUES 
  (1,'Technical University of Munich','Mechatronics','Student'),
  (2,'University College London','Computer Science','Lecturer/Professor'),
  (3,'Heidelberg University - Germany','Computer Networks','Student'),
  (4,'Kadir Has University','Cryptography','Lecturer/Professor'),
  (5,'University of Amsterdam','Web Development','Lecturer/Professor'),
  (6,'University of Oxford','Cyber Security','Student'),
  (7,'Ss. Cyril and Methodius University','Artificial Intelligence','Student'),
  (8,'ETH Zurich','Robotics','Lecturer/Professor'),
  (9,'SRH University of Applied Sciences','Mathematics','Student'),
  (10,'University of Cambridge','Computational Linguistics','Lecturer/Professor'),
  (11,'Heidelberg University - Germany','Data Engineering','Student'),
  (12,'SRH University of Applied Sciences','Computer Networks','Lecturer/Professor'),
  (13,'University of Amsterdam','Web Development','Student'),
  (14,'Technical University of Munich','Artificial Intelligence','Lecturer/Professor'),
  (15,'University College London','Computer Science','Lecturer/Professor'),
  (16,'Ss. Cyril and Methodius University','Robotics','Student'),
  (17,'Kadir Has University','Data Engineering','Lecturer/Professor'),
  (18,'University of Oxford','Mathematics','Student'),
  (19,'University of Cambridge','Cyber Security','Student'),
  (20,'ETH Zurich','Computational Linguistics','Lecturer/Professor'),
  (21,'Ss. Cyril and Methodius University','Cryptography','Student'),
  (22,'University College London','Mechatronics','Lecturer/Professor'),
  (23,'Kadir Has University','Cyber Security','Lecturer/Professor'),
  (24,'University of Oxford','Artificial Intelligence','Student'),
  (25,'ETH Zurich','Computational Linguistics','Student'),
  (26,'University of Amsterdam','Computer Networks','Lecturer/Professor'),
  (27,'University of Cambridge','Cryptography','Lecturer/Professor'),
  (28,'Heidelberg University - Germany','Mathematics','Student'),
  (29,'SRH University of Applied Sciences','Mechatronics','Student'),
  (30,'Technical University of Munich','Robotics','Lecturer/Professor'),
  (31,'Technical University of Munich','Web Development','Student'),
  (32,'Ss. Cyril and Methodius University','Computer Science','Lecturer/Professor'),
  (33,'ETH Zurich','Data Engineering','Student'),
  (34,'Heidelberg University - Germany','Computer Networks','Lecturer/Professor'),
  (35,'University of Oxford','Cyber Security','Student'),
  (36,'University College London','Computer Science','Lecturer/Professor'),
  (37,'SRH University of Applied Sciences','Cryptography','Student'),
  (38,'University of Cambridge','Mathematics','Lecturer/Professor'),
  (39,'Kadir Has University','Web Development','Lecturer/Professor'),
  (40,'University of Amsterdam','Artificial Intelligence','Student'),
  (41,'Heidelberg University - Germany','Computational Linguistics','Lecturer/Professor'),
  (42,'Kadir Has University','Robotics','Student'),
  (43,'University of Amsterdam','Data Engineering','Lecturer/Professor'),
  (44,'University of Oxford','Mechatronics','Student'),
  (45,'Ss. Cyril and Methodius University','Computer Science','Student'),
  (46,'ETH Zurich','Mathematics','Lecturer/Professor'),
  (47,'SRH University of Applied Sciences','Computational Linguistics','Lecturer/Professor'),
  (48,'University of Cambridge','Cryptography','Student'),
  (49,'Technical University of Munich','Web Development','Student'),
  (50,'University College London','Mechatronics','Lecturer/Professor'),
  (51,'SRH University of Applied Sciences','Artificial Intelligence','Lecturer/Professor'),
  (52,'University of Amsterdam','Robotics','Student'),
  (53,'Technical University of Munich','Computer Networks','Lecturer/Professor'),
  (54,'University College London','Data Engineering','Student'),
  (55,'Ss. Cyril and Methodius University','Cyber Security','Lecturer/Professor'),
  (56,'Kadir Has University','Mechatronics','Student'),
  (57,'University of Oxford','Artificial Intelligence','Student'),
  (58,'University of Cambridge','Computer Science','Lecturer/Professor'),
  (59,'ETH Zurich','Cryptography','Student'),
  (60,'Heidelberg University - Germany','Cyber Security','Lecturer/Professor');

UNLOCK TABLES;
